export const cardImages = [
    {"src": "/assets/cards/2diam.png", "val": 2},
    {"src": "/assets/cards/3diam.png", "val": 3}, 
    {"src": "/assets/cards/4diam.png", "val": 4},
    {"src": "/assets/cards/5diam.png", "val": 5},
    {"src": "/assets/cards/6diam.png", "val": 6}, 
    {"src": "/assets/cards/7diam.png", "val": 7},
    {"src": "/assets/cards/8diam.png", "val": 8},
    {"src": "/assets/cards/9diam.png", "val": 9}, 
    {"src": "/assets/cards/10diam.png", "val": 0},
    {"src": "/assets/cards/jdiam.png", "val": 0},
    {"src": "/assets/cards/qdiam.png", "val": 0},
    {"src": "/assets/cards/adiam.png", "val": 0},
  
    {"src": "/assets/cards/2h.png", "val": 2},
    {"src": "/assets/cards/3h.png", "val": 3}, 
    {"src": "/assets/cards/4h.png", "val": 4},
    {"src": "/assets/cards/5h.png", "val": 5},
    {"src": "/assets/cards/6h.png", "val": 6}, 
    {"src": "/assets/cards/7h.png", "val": 7},
    {"src": "/assets/cards/8h.png", "val": 8},
    {"src": "/assets/cards/9h.png", "val": 9}, 
    {"src": "/assets/cards/10h.png", "val": 0},
    {"src": "/assets/cards/jh.png", "val": 0},
    {"src": "/assets/cards/qh.png", "val": 0},
    {"src": "/assets/cards/ah.png", "val": 0},
  
    {"src": "/assets/cards/2sp.png", "val": 2},
    {"src": "/assets/cards/3sp.png", "val": 3}, 
    {"src": "/assets/cards/4sp.png", "val": 4},
    {"src": "/assets/cards/5sp.png", "val": 5},
    {"src": "/assets/cards/6sp.png", "val": 6}, 
    {"src": "/assets/cards/7sp.png", "val": 7},
    {"src": "/assets/cards/8sp.png", "val": 8},
    {"src": "/assets/cards/9sp.png", "val": 9}, 
    {"src": "/assets/cards/10sp.png", "val": 0},
    {"src": "/assets/cards/jsp.png", "val": 0},
    {"src": "/assets/cards/qsp.png", "val": 0},
    {"src": "/assets/cards/asp.png", "val": 0},
  
    {"src": "/assets/cards/2club.png", "val": 2},
    {"src": "/assets/cards/3club.png", "val": 3}, 
    {"src": "/assets/cards/4club.png", "val": 4},
    {"src": "/assets/cards/5club.png", "val": 5},
    {"src": "/assets/cards/6club.png", "val": 6}, 
    {"src": "/assets/cards/7club.png", "val": 7},
    {"src": "/assets/cards/8club.png", "val": 8},
    {"src": "/assets/cards/9club.png", "val": 9}, 
    {"src": "/assets/cards/10club.png", "val": 0},
    {"src": "/assets/cards/jclub.png", "val": 0},
    {"src": "/assets/cards/qclub.png", "val": 0},
    {"src": "/assets/cards/aclub.png", "val": 0},
  ];

export const backside = {"src": "/assets/cards/blank.png", "val": 0}